import React, { useState } from "react";
import uploadPages from "../../../services/page/uploadPagesService";
import { useToast } from "../../../contexts/ToastContext";
import Loading from "../../../common/Loading/Loading";
import "./UploadPagesDropzone.css";

export default function UploadPagesDropzone({
  chapterId,
  onUploadSuccess,
  lastPageNumber = 0,
  activeIndex = 0,
}) {
  const toast = useToast();
  const [isUploading, setIsUploading] = useState(false);
  const [uploadList, setUploadList] = useState([]);

  const handleBulkFileChange = (e) => {
    const files = Array.from(e.target.files);
    if (!files || files.length === 0) return;

    if (files.length > 50) {
      toast.error("Vượt quá giới hạn. Vui lòng chỉ chọn tối đa 50 file.");
      return;
    }

    const sortedFiles = files.sort((a, b) =>
      a.name.localeCompare(b.name, undefined, {
        numeric: true,
        sensitivity: "base",
      }),
    );

    const autoGeneratedList = sortedFiles.map((file, index) => ({
      id: `${Date.now()}-${index}`,
      pageNumber: lastPageNumber + index + 1,
      displayIndex: activeIndex + index,
      sourceFile: file,
      attachedResource: null,
    }));

    setUploadList(autoGeneratedList);
    e.target.value = null;
  };

  const handleUpdateItem = (id, field, value) => {
    setUploadList(
      uploadList.map((item) =>
        item.id === id ? { ...item, [field]: value } : item,
      ),
    );
  };

  const handleRemovePage = (id) => {
    const newList = uploadList
      .filter((item) => item.id !== id)
      .map((item, index) => ({
        ...item,
        displayIndex: activeIndex + index,
        pageNumber: lastPageNumber + index + 1,
      }));

    setUploadList(newList);
  };

  const handleReset = () => {
    setUploadList([]);
  };

  const handleUploadAll = async () => {
    const invalidItems = uploadList.filter(
      (item) => !item.sourceFile || !item.pageNumber,
    );
    if (invalidItems.length > 0) {
      toast.error(
        "Vui lòng đảm bảo tất cả các trang đều có số trang và file bản thảo!",
      );
      return;
    }

    setIsUploading(true);
    let successCount = 0;

    for (let i = 0; i < uploadList.length; i++) {
      const item = uploadList[i];
      try {
        const result = await uploadPages(
          chapterId,
          item.pageNumber,
          item.sourceFile,
          item.attachedResource,
        );

        if (result && result.success !== false) {
          successCount++;
        } else {
          toast.error(
            `Lỗi tải trang số ${item.pageNumber}: ${result?.message || "Thất bại"}`,
          );
        }
      } catch (error) {
        toast.error(`Lỗi hệ thống tại trang số ${item.pageNumber}`);
      }
    }

    setIsUploading(false);

    if (successCount > 0) {
      toast.success(
        `Đã tải lên thành công ${successCount}/${uploadList.length} trang truyện.`,
      );
      onUploadSuccess();
      setUploadList([]);
    }
  };

  return (
    <div className="upload-zone-wrapper">
      {isUploading && (
        <Loading text="Hệ thống đang tải lên từng trang truyện..." />
      )}

      <div className="zone-label">Khu vực tác giả</div>

      {uploadList.length === 0 ? (
        <label className="upload-dropzone">
          <div className="upload-content">
            <span className="upload-text">
              Kéo thả hoặc nhấn để <b>CHỌN LOẠT BẢN THẢO</b>
            </span>
            <span className="upload-subtext">
              Hệ thống sẽ tự động bóc tách và nối tiếp số trang (Tối đa 50 file)
            </span>
          </div>
          <input
            type="file"
            multiple
            onChange={handleBulkFileChange}
            disabled={isUploading}
            className="hidden-input"
          />
        </label>
      ) : (
        <div className="preview-container">
          <p className="preview-notice">
            🔔 Đã tự động nhận diện {uploadList.length} trang. Bạn có thể đính
            kèm file tài nguyên (.zip) nếu cần.
          </p>

          <div className="upload-list">
            {uploadList.map((item) => (
              <div key={item.id} className="upload-item">
                <div className="item-header">
                  <div className="item-title">
                    Trang {item.displayIndex}
                    <span className="file-name-hint">
                      ({item.sourceFile.name})
                    </span>
                  </div>
                  <button
                    className="btn-delete"
                    onClick={() => handleRemovePage(item.id)}
                  >
                    Xóa trang
                  </button>
                </div>

                <div className="file-info-success">
                  ✓ Bản thảo: {item.sourceFile.name} (
                  {(item.sourceFile.size / (1024 * 1024)).toFixed(2)} MB)
                </div>

                <div className="file-attach-group">
                  <span className="file-attach-label">
                    📦 Tài nguyên kèm theo (.zip):
                  </span>
                  <input
                    type="file"
                    accept=".zip,.rar,.7z"
                    className="file-attach-input"
                    onChange={(e) =>
                      handleUpdateItem(
                        item.id,
                        "attachedResource",
                        e.target.files[0],
                      )
                    }
                  />
                </div>
              </div>
            ))}
          </div>

          <div className="action-bar">
            <button
              className="btn-reset"
              onClick={handleReset}
              disabled={isUploading}
            >
              🔄 Chọn lại từ đầu
            </button>
            <button
              className="btn-submit"
              onClick={handleUploadAll}
              disabled={isUploading}
            >
              🚀 Tải lên toàn bộ ({uploadList.length} trang)
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
