name: Manga Project CI/CD
on:
  push:
    branches:
      - main
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Kéo mã nguồn
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Kiểm tra lỗi Backend (Node.js)
        run: |
          echo "Bắt đầu kiểm tra Backend..."
          cd backend
          npm install

      - name: Kiểm tra lỗi Frontend (Next.js)
        run: |
          echo "Bắt đầu build thử Frontend..."
          cd frontend
          npm install
          npm run build
      #  báo cáo kết quả
      - name: Báo cáo Thành công lên Discord
        if: ${{ success() && secrets.DISCORD_WEBHOOK_URL != '' }}
        run: |
          curl -H "Content-Type: application/json" \
          -d '{"content": "**[THÀNH CÔNG]** Có code mới đẩy lên nhánh `main`. Đã kiểm tra Backend và build Next.js thành công không có lỗi! 🚀", "username": "CI/CD mangaer"}' \
          ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Báo cáo Thất bại lên Discord
        if: ${{ failure() && secrets.DISCORD_WEBHOOK_URL != '' }}
        run: |
          curl -H "Content-Type: application/json" \
